# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ master ]

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
    - name: Run Tests
      run: |
           docker run -v $(pwd):/app -t jessemalone/webrtcjam-build \
           /bin/bash -c "cd /app && npm install && npm test -- --watchAll=false"
  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
    - name: Run Tests
      run: |
           docker run -v $(pwd):/app -t jessemalone/webrtcjam-build \
           /bin/bash -c "cd /app/server && make install && make test"
